language: python
sudo: false
python:
- '2.7'
- '3.5'
- '3.6'
- '3.7'
install:
- pip install -r requirements-dev.txt
- pip install .
script: py.test src/geventhttpclient/tests
jobs:
  include:
  - stage: build
    sudo: required
    services:
    - docker
    os: linux
    python: '3.6'
    install:
    - pip install cibuildwheel==0.8.0
    script:
    - cibuildwheel --output-dir wheelhouse
    - if [ "${TRAVIS_TAG:-}" != "" ]; then pip install twine; python -m twine upload
      --skip-existing wheelhouse/*; fi
    env:
    - CIBW_SKIP=cp33
deploy:
  provider: pypi
  user: __token__
  password: "$TWINE_TOKEN0$TWINE_TOKEN1$TWINE_TOKEN2"
  distributions: sdist
  on:
    tags: true
env:
  global:
  - secure: aNOiDvBeWT0eO3bI60Xps5fR3GuKh83kESA+zvWvLI3f2N/jXGGM17bSbSRFJvpTLSCeLFmn0wLG28Q4vZHMHsfTvBtYmLCA06IMuh4vgU4TWRS62GhRR5FCn7NN3XDY8lSA1MOBGERQ16LYXYG+uVK5G1hFb6iqZs0ActsAwn0=
  - secure: TtNdqjEKxxXPabDFAoqP/Vkx3Lr6FlWV3Vb9K3xKsojXgTEyTFLVQyRgufegqus0CviC9Q06hzITJ6VjL5yAjIcE3Zwmt3d1NBvkoIY/4HGBXTt0Wla6wLZ4DikmXygjibDZmc8A8gsC1y/4BPyTx+2nGgUi7owqt9JeK87AZxo=
  - secure: IM2exBCtdZmmUgCKh9XHjohAaamXf1YB3EBVkez00XGDZo1fRWEz3mO9B7TtA1xfQQfD0eM3q89R9cVNNqX09+5MA6Ac7G04dtxYAe5WkO5phFCi9EufPCqoGS6TwuniJjHi/39QVh2R4MAQ/GwXXnSbmWLpY7bhChiQRmHTiLY=
